version: '3.8'
services:
  app:
    image: record_app:latest
    tty: true
    working_dir: /
    ports:
      - "8080:8080"
    environment:
      # mysqlの接続設定 host:portはコンテナ名指定
      spring.datasource.driverClassName: "com.mysql.cj.jdbc.Driver"
      spring.datasource.url: "jdbc:mysql://mysqlserver/record_app"
      spring.datasource.username: "root"
      spring.datasource.password: "root"
    depends_on:
      mysqlserver:
        condition: service_started
    networks:
      app:
  mysqlserver:
    image: mysql:8.0.31
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=record_app
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/log:/var/log/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      app:
networks:
  app:
